name = "LeanLanguage"
version = "0.1.0"
defaultTargets = ["leanlanguage"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.26.0"

[[lean_lib]]
name = "LeanLanguage"

[[lean_exe]]
name = "leanlanguage"
root = "Main"
